# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Job definition templates

  baseline-job: &baseline-job
    template: baseline.jinja2
    kind: job
    kcidb_test_suite: boot

  kbuild-job: &kbuild-job
    template: kbuild.jinja2
    kind: kbuild
    rules:
      tree:
      - '!android'
      - '!chromiumos'

  kbuild-clang-17-arm64-job: &kbuild-clang-17-arm64-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}clang-17:arm64-kselftest-kernelci
    params: &kbuild-clang-17-arm64-params
      arch: arm64
      compiler: clang-17
      cross_compile: 'aarch64-linux-gnu-'
      defconfig: defconfig

  kbuild-clang-17-x86-job: &kbuild-clang-17-x86-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}clang-17:x86-kselftest-kernelci
    params: &kbuild-clang-17-x86-params
      arch: x86_64
      compiler: clang-17
      defconfig: x86_64_defconfig

  kbuild-gcc-12-arm64-job: &kbuild-gcc-12-arm64-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}gcc-12:arm64-kselftest-kernelci
    params: &kbuild-gcc-12-arm64-params
      arch: arm64
      compiler: gcc-12
      cross_compile: 'aarch64-linux-gnu-'
      defconfig: defconfig
      fragments:
        - 'lab-setup'
        - 'kselftest'

  kbuild-gcc-12-x86-job: &kbuild-gcc-12-x86-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}gcc-12:x86-kselftest-kernelci
    params: &kbuild-gcc-12-x86-params
      arch: x86_64
      compiler: gcc-12
      defconfig: x86_64_defconfig
      fragments:
        - 'kselftest'

  kvm-unit-tests-job: &kvm-unit-tests-job
    template: kvm-unit-tests.jinja2
    kind: job
    params: &kvm-unit-tests-params
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-kvm-unit-tests/20250624.0/{debarch}'
    kcidb_test_suite: kvm-unit-tests
    rules:
      fragments:
        - '!kselftest'

  ltp-job: &ltp-job
    template: ltp.jinja2
    kind: job
    params: &ltp-params
      boot_commands: nfs
      nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/bookworm-ltp/20250818.0/{debarch}'
      skip_install: "true"
      skipfile: skipfile-lkft.yaml
      workers: max
    kcidb_test_suite: ltp
    rules:
      fragments:
        - '!kselftest'

### Frequently used rules

  # A list of trees for which to run the build-only jobs.
  build-only-trees-rules: &build-only-trees-rules
    # NOTE: Please keep the trees list in sorted order.
    tree:
    - 'amlogic'
    - 'ardb'
    - 'arnd'
    - 'cip'
    - 'clk'
    - 'efi'
    - 'khilman'
    - 'krzysztof'
    - 'lee-backlight'
    - 'linusw'
    - 'linux-pci'
    - 'net-next'
    - 'next'
    - 'pm'
    - 'qcom'
    - 'qcom-next'
    - 'renesas'
    - 'robh'
    - 'rppt'
    - 'sashal-next'
    - 'soc'
    - 'stable'
    - 'tegra'
    - 'thermal'
    - 'tip'
    - 'ulfh'
    - 'vireshk'

