_anchors:
  baseline-job: &baseline-job
    template: baseline.jinja2
    kind: job
    kcidb_test_suite: boot

  kbuild-job: &kbuild-job
    template: kbuild.jinja2
    kind: kbuild
    rules:
      tree:
      - '!android'
      - '!chromiumos'

  kbuild-gcc-12-arm: &kbuild-gcc-12-arm-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}gcc-12:arm-kselftest-kernelci
    params: &kbuild-gcc-12-arm-params
      arch: arm
      compiler: gcc-12
      cross_compile: 'arm-linux-gnueabihf-'
      defconfig: multi_v7_defconfig

  kbuild-gcc-12-arm64: &kbuild-gcc-12-arm64-job
    <<: *kbuild-job
    image: ghcr.io/kernelci/{image_prefix}gcc-12:arm64-kselftest-kernelci
    params: &kbuild-gcc-12-arm64-params
      arch: arm64
      compiler: gcc-12
      cross_compile: 'aarch64-linux-gnu-'
      defconfig: defconfig
      fragments:
        - 'lab-setup'
        - 'kselftest'

jobs:
