_anchors:

  arm64-device: &arm64-device
    arch: arm64
    boot_method: u-boot

  arm-device: &arm-device
    <<: *arm64-device
    arch: arm

  riscv-device: &riscv-device
    arch: riscv
    boot_method: u-boot

  x86_64-device: &x86_64-device
    arch: x86_64
    boot_method: grub
    mach: x86

platforms:
# arm64 platforms
  zynqmp-zcu102:
    <<: *arm64-device
    mach: zynqmp
    dtb: dtbs/xilinx/zynqmp-zcu102-rev1.0.dtb
    compatible: ['xlnx,zynqmp-zcu102-rev1.0', 'xlnx,zynqmp-zcu102', 'xlnx,zynqmp']
