_anchors:

  arm64-device: &arm64-device
    arch: arm64
    boot_method: u-boot

  arm-device: &arm-device
    <<: *arm64-device
    arch: arm

  riscv-device: &riscv-device
    arch: riscv
    boot_method: u-boot

  x86_64-device: &x86_64-device
    arch: x86_64
    boot_method: grub
    mach: x86

platforms:
