# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022, 2023 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

# Not directly loaded into the config, only used for YAML aliases in this file
_anchors:

### Scheduler definition helpers
  build-k8s-all: &build-k8s-all
    event: &checkout-event
      channel: node
      kind: checkout
      state: available
    runtime:
      name: k8s-all

  node-event: &node-event-kbuild
    channel: node
    kind: kbuild
    state: available

  node-event-kbuild-done: &node-event-kbuild-done
    <<: *node-event-kbuild
    state: done
    result: pass

  job-event: &job-event
    channel: node
    state: done
    kind: job

