trees:

  # NOTE: Please keep the trees list below in sorted order.


# -----------------------------------------------------------------------------
# Legacy configuration data (still used by trigger service)
#

build_environments:

  gcc-12:
    cc: gcc
    cc_version: 10
    arch_params:
      x86_64:
        name: 'x86'


build_variants:
  variants:
    gcc-12:
      build_environment: gcc-12
      architectures:
        x86_64:
          base_defconfig: 'x86_64_defconfig'
          filters:
            - regex: { defconfig: 'x86_64_defconfig' }
        arm64:
          base_defconfig: 'defconfig'
          filters:
            - regex: { defconfig: 'defconfig' }
        arm:
          base_defconfig: 'multi_v7_defconfig'
          filters:
            - regex: { defconfig: 'multi_v7_defconfig' }
